<a href="https://colab.research.google.com/github/Dathanarayana/PDS-2303A51754-B-11-/blob/main/lab_3_14_aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

data = np.array([[78, 85, 92, 88],

                 [67, 74, 81, 79],

                 [90, 95, 89, 84],

                 [76, 80, 85, 83]])

row_mean = np.mean(data, axis=1)

col_mean = np.mean(data, axis=0)

std_dev = np.std(data)

variance = np.var(data)

global_max = np.max(data)

global_min = np.min(data)

max_index = np.unravel_index(np.argmax(data), data.shape)

min_index = np.unravel_index(np.argmin(data), data.shape)

print("Data:\n", data)

print("Row-wise mean:", row_mean)

print("Column-wise mean:", col_mean)

print("Standard Deviation:", std_dev)

print("Variance:", variance)

print("Global Max:", global_max, "at index", max_index)

print("Global Min:", global_min, "at index", min_index)

Data:
 [[78 85 92 88]
 [67 74 81 79]
 [90 95 89 84]
 [76 80 85 83]]
Row-wise mean: [85.75 75.25 89.5  81.  ]
Column-wise mean: [77.75 83.5  86.75 83.5 ]
Standard Deviation: 6.9988838395847095
Variance: 48.984375
Global Max: 95 at index (np.int64(2), np.int64(1))
Global Min: 67 at index (np.int64(1), np.int64(0))


In [ ]:
import numpy as np

image = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)

red_channel = image[:, :, 0]

green_channel = image[:, :, 1]

blue_channel = image[:, :, 2]

avg_red = np.mean(red_channel)

avg_green = np.mean(green_channel)

avg_blue = np.mean(blue_channel)

brightened = np.clip(image + 50, 0, 255)

print("Original Image:\n", image)

print("Red Channel:\n", red_channel)

print("Green Channel:\n", green_channel)

print("Blue Channel:\n", blue_channel)

print("Average Red Intensity:", avg_red)

print("Average Green Intensity:", avg_green)

print("Average Blue Intensity:", avg_blue)

print("Brightened Image:\n", brightened)

Original Image:
 [[[249 130 103]
  [ 14 241 221]
  [214 111 235]]

 [[222 131   9]
  [248  96   0]
  [111 147  35]]

 [[ 58  81 234]
  [185 132 186]
  [ 95  71 208]]]
Red Channel:
 [[249  14 214]
 [222 248 111]
 [ 58 185  95]]
Green Channel:
 [[130 241 111]
 [131  96 147]
 [ 81 132  71]]
Blue Channel:
 [[103 221 235]
 [  9   0  35]
 [234 186 208]]
Average Red Intensity: 155.11111111111111
Average Green Intensity: 126.66666666666667
Average Blue Intensity: 136.77777777777777
Brightened Image:
 [[[ 43 180 153]
  [ 64  35  15]
  [  8 161  29]]

 [[ 16 181  59]
  [ 42 146  50]
  [161 197  85]]

 [[108 131  28]
  [235 182 236]
  [145 121   2]]]
